<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of available Bible organizational systems including
    A unique English organizational system name (as a comment only)
        (This table should be language agnostic although English is used as a meta-language.)
    A unique reference abbreviation
    The type:   original    e.g., Hebrew/Greek scriptures
                translation e.g., 1611grep  King James Version (KJV)
                revision    e.g., 1769 King James Version
                edition     e.g., NIV Women's Study Bible (An edition uses a translation)
    The definitive names with the language specified as an ISO 639-3 code in an attribute.
    A versificationSystem name field which directs to that versification system.
    A punctuationSystem name field which directs to the punctuation system.
        None and Unknown are also valid entries for the system name fields.

The data is preceded by a header of the same format as an OSIS header.

Note that most of the data is supplied as XML elements, not attributes.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleOrganizationalSystems [
    <!ELEMENT BibleOrganizationalSystems (header,BibleOrganizationalSystem+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier*,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|cre|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleOrganizationalSystem (referenceAbbreviation,languageCode,name+,publicationDate*,versificationSystem*,punctuationSystem*,bookOrderSystem*,booksNamesSystem*,derivedFrom*,usesText*)>
            <!ATTLIST BibleOrganizationalSystem type CDATA #REQUIRED>
            <!ELEMENT referenceAbbreviation (#PCDATA)>
            <!ELEMENT languageCode (#PCDATA)>
            <!ELEMENT name (#PCDATA)>
            <!ELEMENT publicationDate (#PCDATA)>
            <!ELEMENT versificationSystem (#PCDATA)>
            <!ELEMENT punctuationSystem (#PCDATA)>
            <!ELEMENT bookOrderSystem (#PCDATA)>
            <!ELEMENT booksNamesSystem (#PCDATA)>
            <!ELEMENT derivedFrom (#PCDATA)>
            <!ELEMENT usesText (#PCDATA)>
]>

<BibleOrganizationalSystems>

  <header>
    <work>
      <version>0.14</version>
      <date>2011-01-17</date>
      <title>Bible organizational systems list</title>
      <contributor role="com">Robert Hunt</contributor>
      <rights>Public Domain</rights>
    </work>
  </header>


<!-- Original Bible texts -->
  <BibleOrganizationalSystem type="original">
    <referenceAbbreviation>HEB</referenceAbbreviation>
    <languageCode>hbo</languageCode>
    <name>Hebrew Scriptures</name>
    <versificationSystem>Hebrew</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Hebrew</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
  </BibleOrganizationalSystem>

  <BibleOrganizationalSystem type="original">
    <referenceAbbreviation>NTG</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Greek Scriptures</name>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Unknown</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
  </BibleOrganizationalSystem>


<!-- Translations from originals -->
  <BibleOrganizationalSystem type="translation">
    <referenceAbbreviation>LXX</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Septuagint</name>
    <name>LXX</name>
    <publicationDate>300 BC</publicationDate>
    <versificationSystem>Septuagint</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Septuagint</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
  </BibleOrganizationalSystem>

  <BibleOrganizationalSystem type="translation">
    <referenceAbbreviation>KJV-1611</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>King James Version</name>
    <name>Authorized Version</name>
    <publicationDate>1611</publicationDate>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanProtestantBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
  </BibleOrganizationalSystem>

  <BibleOrganizationalSystem type="translation">
    <referenceAbbreviation>ASV</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>American Standard Version</name>
    <publicationDate>1901</publicationDate>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanProtestantBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
  </BibleOrganizationalSystem>

  <BibleOrganizationalSystem type="translation">
    <referenceAbbreviation>MBT</referenceAbbreviation>
    <languageCode>mbt</languageCode>
    <name>Matigsalug</name>
    <publicationDate>2010</publicationDate>
    <versificationSystem>RSV52</versificationSystem>
    <punctuationSystem>Matigsalug</punctuationSystem>
    <bookOrderSystem>EuropeanProtestantBible</bookOrderSystem>
    <booksNamesSystem>mbt</booksNamesSystem>
  </BibleOrganizationalSystem>


<!-- Revisions of earlier translations -->
  <BibleOrganizationalSystem type="revision">
    <referenceAbbreviation>KJV-1769</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>King James Version</name>
    <name>Authorized Version</name>
    <publicationDate>1769</publicationDate>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanProtestantBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <derivedFrom>KJV-1611</derivedFrom>
  </BibleOrganizationalSystem>

  <BibleOrganizationalSystem type="revision">
    <referenceAbbreviation>RSV52</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Revised Standard Version</name>
    <publicationDate>1952</publicationDate>
    <versificationSystem>RSV52</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanProtestantBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <derivedFrom>ASV</derivedFrom>
  </BibleOrganizationalSystem>


<!-- Bible editions that use one or more of the above translations and/or originals -->
  <BibleOrganizationalSystem type="edition">
    <referenceAbbreviation>KJV-1611</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>King James Version</name>
    <name>Authorized Version</name>
    <publicationDate>1611</publicationDate>
    <usesText>KJV-1611</usesText>
  </BibleOrganizationalSystem>

  <BibleOrganizationalSystem type="edition">
    <referenceAbbreviation>KJV-1769</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>King James Version</name>
    <name>Authorized Version</name>
    <publicationDate>1769</publicationDate>
    <usesText>KJV-1769</usesText>
  </BibleOrganizationalSystem>

  <BibleOrganizationalSystem type="edition">
    <referenceAbbreviation>RSV</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Revised Standard Version</name>
    <publicationDate>1952</publicationDate>
    <usesText>RSV52</usesText>
  </BibleOrganizationalSystem>

  <BibleOrganizationalSystem type="edition">
    <referenceAbbreviation>MBT</referenceAbbreviation>
    <languageCode>mbt</languageCode>
    <name>Matigsalug NT+</name>
    <publicationDate>2011</publicationDate>
    <usesText>MBT</usesText>
  </BibleOrganizationalSystem>

</BibleOrganizationalSystems>
