<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of Bible booknames codes including
these three compulsory fields:
    An English book name (as a comment only)
        (The information in this table should be language agnostic although English is used as a meta-language.)
        (It should also be independent of any theological judgements but mostly based on historical publications.)
    A three character reference code (upper case, no spaces, begins with a letter)
        This reference code should reflect book contents (not book names) and is used to link to other tables.
        These reference codes are guaranteed to be stable after V1.00
            i.e., they will not change or be reused for different books.
    A reference number (1..255 for processing only - not necessarily sequential)
        Reference numbers are guaranteed to be stable after V1.00
            i.e., they will not change or be reused for different books.
        Can be used as a unique ID instead of the reference code if you prefer an integer.
        1..66 are guaranteed to match the common Protestant Bible book orders.
        200..255 are reserved for user defined books.
and then these optional fields (optional because not all systems handle the less common books)
    The SBL abbreviation (can include spaces)
    The OSIS abbrevation (no spaces but may begin with a digit)
    The 1-2 digit CCEL id number
    The three-character Paratext abbreviation (no spaces but may begin with a digit)
    The two-digit Paratext number
    The three-character NET Bible abbreviation
    The Sword abbreviation
All of the above fields should individually be unique,
    i.e., there should never be a duplicate entry for any given data field
        although there may be duplicates across differently named fields.

Deutero-canonical/Apocryphal and less common books are included.
"Combined" books are included.
This table does not infer any information about the presence or the order of the books within any particular Bible version.
This table does not infer any information about the number of chapters (or verses) in any given book.
There should be exactly one entry for each possible Bible book which is printed separately in some publications
    and one entry for each possible combination of those Bible books.
For example:
    If Ezra and Nehemiah are sometimes published as invididual books, and sometimes combined, there should be 3 entries in this database.
    If Hebrew Esther and Greek Esther are sometimes published as invididual books, and sometimes combined, there should be 3 entries in this database.
        However, if Greek Esther was never published singly, but only in combination with Hebrew Esther, there would only be 2 entries (Hebrew Esther and Combined Esther).
    If some publications include Ps.151 as an extra chapter, that is not a reason to include a book for 151 chapters of Psalms here (we can just regard it as a chapter variation)
        but if some publications publish it as a separate book, we would need to include 3 entries here (150 Psalms, Ps 151 only, 151 Psalms).
    This is because mappings between Bible books in different publication will be dependent on this file.
        (If it's JUST chapter mapping, that's handled elsewhere).
    If a book is a translation of another book, that is not usually a good enough reason to include multiple entries here
        (unless say, both the Hebrew and the Greek versions were published in the same "Bible").

This file can never adequately represent all possible historical Bible books codes (and their mappings),
    especially since it attempts to avoid including historic codes which were not consistent or logical.

The data is preceded by a header of the same format as an OSIS header.

Note that the data is supplied as XML elements (not attributes).

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied BibleBooksCodes.ReadMe.txt for more details.
-->

<!DOCTYPE BibleBooksCodes [
    <!ELEMENT BibleBooksCodes (header,BibleBookCodes+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier+,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleBookCodes (nameEnglish,referenceAbbreviation,referenceNumber,SBLAbbreviation?,OSISAbbreviation?,CCELNumber?,ParatextAbbreviation?,ParatextNumber?,NETBibleAbbreviation?,SwordAbbreviation?)>
            <!ELEMENT nameEnglish (#PCDATA)>
            <!ELEMENT referenceAbbreviation (#PCDATA)>
            <!ELEMENT referenceNumber (#PCDATA)>
            <!ELEMENT SBLAbbreviation (#PCDATA)>
            <!ELEMENT OSISAbbreviation (#PCDATA)>
            <!ELEMENT CCELNumber (#PCDATA)>
            <!ELEMENT ParatextAbbreviation (#PCDATA)>
            <!ELEMENT ParatextNumber (#PCDATA)>
            <!ELEMENT NETBibleAbbreviation (#PCDATA)>
            <!ELEMENT SwordAbbreviation (#PCDATA)>
]>

<BibleBooksCodes>

  <header>
    <work>
      <version>0.90</version>
      <date>2010-11-08</date>
      <title>Bible books codes list</title>
      <contributor role="com">Robert Hunt</contributor>
      <identifier type="URL">http://www.sbl-site.org/publications/publishingwithsbl.aspx</identifier>
      <identifier type="URL">http://www.bibletechnologies.net</identifier>
      <identifier type="URL">http://lc.bfbs.org.uk/news.php?item.9.4</identifier>
      <identifier type="URL">http://lc.bfbs.org.uk/request.php?canonicalissuesinparatext.pdf</identifier>
      <rights>Public Domain</rights>
    </work>
  </header>

<!-- Old Testament -->
  <BibleBookCodes>
    <nameEnglish>Genesis / 1 Moses</nameEnglish>
    <referenceAbbreviation>GEN</referenceAbbreviation>
    <referenceNumber>1</referenceNumber>
    <SBLAbbreviation>Gen</SBLAbbreviation>
    <OSISAbbreviation>Gen</OSISAbbreviation>
    <CCELNumber>1</CCELNumber>
    <ParatextAbbreviation>Gen</ParatextAbbreviation>
    <ParatextNumber>01</ParatextNumber>
    <NETBibleAbbreviation>Gen</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Exodus / 2 Moses</nameEnglish>
    <referenceAbbreviation>EXO</referenceAbbreviation>
    <referenceNumber>2</referenceNumber>
    <SBLAbbreviation>Exod</SBLAbbreviation>
    <OSISAbbreviation>Exod</OSISAbbreviation>
    <CCELNumber>2</CCELNumber>
    <ParatextAbbreviation>Exo</ParatextAbbreviation>
    <ParatextNumber>02</ParatextNumber>
    <NETBibleAbbreviation>Exo</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Leviticus / 3 Moses</nameEnglish>
    <referenceAbbreviation>LEV</referenceAbbreviation>
    <referenceNumber>3</referenceNumber>
    <SBLAbbreviation>Lev</SBLAbbreviation>
    <OSISAbbreviation>Lev</OSISAbbreviation>
    <CCELNumber>3</CCELNumber>
    <ParatextAbbreviation>Lev</ParatextAbbreviation>
    <ParatextNumber>03</ParatextNumber>
    <NETBibleAbbreviation>Lev</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Numbers / 4 Moses</nameEnglish>
    <referenceAbbreviation>NUM</referenceAbbreviation>
    <referenceNumber>4</referenceNumber>
    <SBLAbbreviation>Num</SBLAbbreviation>
    <OSISAbbreviation>Num</OSISAbbreviation>
    <CCELNumber>4</CCELNumber>
    <ParatextAbbreviation>Num</ParatextAbbreviation>
    <ParatextNumber>04</ParatextNumber>
    <NETBibleAbbreviation>Num</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Deuteronomy / 5 Moses</nameEnglish>
    <referenceAbbreviation>DEU</referenceAbbreviation>
    <referenceNumber>5</referenceNumber>
    <SBLAbbreviation>Deut</SBLAbbreviation>
    <OSISAbbreviation>Deut</OSISAbbreviation>
    <CCELNumber>5</CCELNumber>
    <ParatextAbbreviation>Deu</ParatextAbbreviation>
    <ParatextNumber>05</ParatextNumber>
    <NETBibleAbbreviation>Deu</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Joshua</nameEnglish>
    <referenceAbbreviation>JOS</referenceAbbreviation>
    <referenceNumber>6</referenceNumber>
    <SBLAbbreviation>Josh</SBLAbbreviation>
    <OSISAbbreviation>Josh</OSISAbbreviation>
    <CCELNumber>6</CCELNumber>
    <ParatextAbbreviation>Jos</ParatextAbbreviation>
    <ParatextNumber>06</ParatextNumber>
    <NETBibleAbbreviation>Jos</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Judges</nameEnglish>
    <referenceAbbreviation>JDG</referenceAbbreviation>
    <referenceNumber>7</referenceNumber>
    <SBLAbbreviation>Judg</SBLAbbreviation>
    <OSISAbbreviation>Judg</OSISAbbreviation>
    <CCELNumber>7</CCELNumber>
    <ParatextAbbreviation>Jdg</ParatextAbbreviation>
    <ParatextNumber>07</ParatextNumber>
    <NETBibleAbbreviation>Jdg</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Ruth</nameEnglish>
    <referenceAbbreviation>RUT</referenceAbbreviation>
    <referenceNumber>8</referenceNumber>
    <SBLAbbreviation>Ruth</SBLAbbreviation>
    <OSISAbbreviation>Ruth</OSISAbbreviation>
    <CCELNumber>8</CCELNumber>
    <ParatextAbbreviation>Rut</ParatextAbbreviation>
    <ParatextNumber>08</ParatextNumber>
    <NETBibleAbbreviation>Rut</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Samuel / 1 Kingdoms / 1 Kings</nameEnglish>
    <referenceAbbreviation>SA1</referenceAbbreviation>
    <referenceNumber>9</referenceNumber>
    <SBLAbbreviation>1 Sam</SBLAbbreviation>
    <OSISAbbreviation>1Sam</OSISAbbreviation>
    <CCELNumber>9</CCELNumber>
    <ParatextAbbreviation>1Sa</ParatextAbbreviation>
    <ParatextNumber>09</ParatextNumber>
    <NETBibleAbbreviation>1Sa</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>2 Samuel / 2 Kingdoms / 2 Kings</nameEnglish>
    <referenceAbbreviation>SA2</referenceAbbreviation>
    <referenceNumber>10</referenceNumber>
    <SBLAbbreviation>2 Sam</SBLAbbreviation>
    <OSISAbbreviation>2Sam</OSISAbbreviation>
    <CCELNumber>10</CCELNumber>
    <ParatextAbbreviation>2Sa</ParatextAbbreviation>
    <ParatextNumber>10</ParatextNumber>
    <NETBibleAbbreviation>2Sa</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Kings / 3 Kingdoms / 3 Kings</nameEnglish>
    <referenceAbbreviation>KI1</referenceAbbreviation>
    <referenceNumber>11</referenceNumber>
    <SBLAbbreviation>1 Kgs</SBLAbbreviation>
    <OSISAbbreviation>1Kgs</OSISAbbreviation>
    <CCELNumber>11</CCELNumber>
    <ParatextAbbreviation>1Ki</ParatextAbbreviation>
    <ParatextNumber>11</ParatextNumber>
    <NETBibleAbbreviation>1Ki</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>2 Kings / 4 Kingdoms / 4 Kings</nameEnglish>
    <referenceAbbreviation>KI2</referenceAbbreviation>
    <referenceNumber>12</referenceNumber>
    <SBLAbbreviation>2 Kgs</SBLAbbreviation>
    <OSISAbbreviation>2Kgs</OSISAbbreviation>
    <CCELNumber>12</CCELNumber>
    <ParatextAbbreviation>2Ki</ParatextAbbreviation>
    <ParatextNumber>12</ParatextNumber>
    <NETBibleAbbreviation>2Ki</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Chronicles/Paralipomenon</nameEnglish>
    <referenceAbbreviation>CH1</referenceAbbreviation>
    <referenceNumber>13</referenceNumber>
    <SBLAbbreviation>1 Chr</SBLAbbreviation>
    <OSISAbbreviation>1Chr</OSISAbbreviation>
    <CCELNumber>13</CCELNumber>
    <ParatextAbbreviation>1Ch</ParatextAbbreviation>
    <ParatextNumber>13</ParatextNumber>
    <NETBibleAbbreviation>1Ch</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>2 Chronicles/Paralipomenon</nameEnglish>
    <referenceAbbreviation>CH2</referenceAbbreviation>
    <referenceNumber>14</referenceNumber>
    <SBLAbbreviation>2 Chr</SBLAbbreviation>
    <OSISAbbreviation>2Chr</OSISAbbreviation>
    <CCELNumber>14</CCELNumber>
    <ParatextAbbreviation>2Ch</ParatextAbbreviation>
    <ParatextNumber>14</ParatextNumber>
    <NETBibleAbbreviation>2Ch</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <!-- Don't use this for combined Ezra-Nehemiah (use EZN) -->
    <nameEnglish>Ezra</nameEnglish>
    <referenceAbbreviation>EZR</referenceAbbreviation>
    <referenceNumber>15</referenceNumber>
    <SBLAbbreviation>Ezra</SBLAbbreviation>
    <OSISAbbreviation>Ezra</OSISAbbreviation>
    <CCELNumber>15</CCELNumber>
    <ParatextAbbreviation>Ezr</ParatextAbbreviation>
    <ParatextNumber>15</ParatextNumber>
    <NETBibleAbbreviation>Ezr</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Nehemiah</nameEnglish>
    <referenceAbbreviation>NEH</referenceAbbreviation>
    <referenceNumber>16</referenceNumber>
    <SBLAbbreviation>Neh</SBLAbbreviation>
    <OSISAbbreviation>Neh</OSISAbbreviation>
    <CCELNumber>16</CCELNumber>
    <ParatextAbbreviation>Neh</ParatextAbbreviation>
    <ParatextNumber>16</ParatextNumber>
    <NETBibleAbbreviation>Neh</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Esther</nameEnglish>
    <referenceAbbreviation>EST</referenceAbbreviation>
    <referenceNumber>17</referenceNumber>
    <SBLAbbreviation>Esth</SBLAbbreviation>
    <OSISAbbreviation>Esth</OSISAbbreviation>
    <CCELNumber>17</CCELNumber>
    <ParatextAbbreviation>Est</ParatextAbbreviation>
    <ParatextNumber>17</ParatextNumber>
    <NETBibleAbbreviation>Est</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Job</nameEnglish>
    <referenceAbbreviation>JOB</referenceAbbreviation>
    <referenceNumber>18</referenceNumber>
    <SBLAbbreviation>Job</SBLAbbreviation>
    <OSISAbbreviation>Job</OSISAbbreviation>
    <CCELNumber>18</CCELNumber>
    <ParatextAbbreviation>Job</ParatextAbbreviation>
    <ParatextNumber>18</ParatextNumber>
    <NETBibleAbbreviation>Job</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Psalms / Gallicanum / Psalms A</nameEnglish>
    <referenceAbbreviation>PSA</referenceAbbreviation>
    <referenceNumber>19</referenceNumber>
    <SBLAbbreviation>Ps</SBLAbbreviation>
    <OSISAbbreviation>Ps</OSISAbbreviation>
    <CCELNumber>19</CCELNumber>
    <ParatextAbbreviation>Psa</ParatextAbbreviation>
    <ParatextNumber>19</ParatextNumber>
    <NETBibleAbbreviation>Psa</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Proverbs</nameEnglish>
    <referenceAbbreviation>PRO</referenceAbbreviation>
    <referenceNumber>20</referenceNumber>
    <SBLAbbreviation>Prov</SBLAbbreviation>
    <OSISAbbreviation>Prov</OSISAbbreviation>
    <CCELNumber>20</CCELNumber>
    <ParatextAbbreviation>Pro</ParatextAbbreviation>
    <ParatextNumber>20</ParatextNumber>
    <NETBibleAbbreviation>Pro</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Ecclesiastes/Qoholeth</nameEnglish>
    <referenceAbbreviation>ECC</referenceAbbreviation>
    <referenceNumber>21</referenceNumber>
    <SBLAbbreviation>Eccl</SBLAbbreviation>
    <OSISAbbreviation>Eccl</OSISAbbreviation>
    <CCELNumber>21</CCELNumber>
    <ParatextAbbreviation>Ecc</ParatextAbbreviation>
    <ParatextNumber>21</ParatextNumber>
    <NETBibleAbbreviation>Ecc</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Song of Solomon / Song of Songs / Canticles</nameEnglish>
    <referenceAbbreviation>SNG</referenceAbbreviation>
    <referenceNumber>22</referenceNumber>
    <SBLAbbreviation>Song</SBLAbbreviation>
    <OSISAbbreviation>Song</OSISAbbreviation>
    <CCELNumber>22</CCELNumber>
    <ParatextAbbreviation>Sng</ParatextAbbreviation>
    <ParatextNumber>22</ParatextNumber>
    <NETBibleAbbreviation>Sos</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Isaiah</nameEnglish>
    <referenceAbbreviation>ISA</referenceAbbreviation>
    <referenceNumber>23</referenceNumber>
    <SBLAbbreviation>Isa</SBLAbbreviation>
    <OSISAbbreviation>Isa</OSISAbbreviation>
    <CCELNumber>23</CCELNumber>
    <ParatextAbbreviation>Isa</ParatextAbbreviation>
    <ParatextNumber>23</ParatextNumber>
    <NETBibleAbbreviation>Isa</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Jeremiah</nameEnglish>
    <referenceAbbreviation>JER</referenceAbbreviation>
    <referenceNumber>24</referenceNumber>
    <SBLAbbreviation>Jer</SBLAbbreviation>
    <OSISAbbreviation>Jer</OSISAbbreviation>
    <CCELNumber>24</CCELNumber>
    <ParatextAbbreviation>Jer</ParatextAbbreviation>
    <ParatextNumber>24</ParatextNumber>
    <NETBibleAbbreviation>Jer</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Lamentations</nameEnglish>
    <referenceAbbreviation>LAM</referenceAbbreviation>
    <referenceNumber>25</referenceNumber>
    <SBLAbbreviation>Lam</SBLAbbreviation>
    <OSISAbbreviation>Lam</OSISAbbreviation>
    <CCELNumber>25</CCELNumber>
    <ParatextAbbreviation>Lam</ParatextAbbreviation>
    <ParatextNumber>25</ParatextNumber>
    <NETBibleAbbreviation>Lam</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Ezekiel</nameEnglish>
    <referenceAbbreviation>EZK</referenceAbbreviation>
    <referenceNumber>26</referenceNumber>
    <SBLAbbreviation>Ezek</SBLAbbreviation>
    <OSISAbbreviation>Ezek</OSISAbbreviation>
    <CCELNumber>26</CCELNumber>
    <ParatextAbbreviation>Ezk</ParatextAbbreviation>
    <ParatextNumber>26</ParatextNumber>
    <NETBibleAbbreviation>Eze</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Daniel</nameEnglish>
    <referenceAbbreviation>DAN</referenceAbbreviation>
    <referenceNumber>27</referenceNumber>
    <SBLAbbreviation>Dan</SBLAbbreviation>
    <OSISAbbreviation>Dan</OSISAbbreviation>
    <CCELNumber>27</CCELNumber>
    <ParatextAbbreviation>Dan</ParatextAbbreviation>
    <ParatextNumber>27</ParatextNumber>
    <NETBibleAbbreviation>Dan</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Hosea</nameEnglish>
    <referenceAbbreviation>HOS</referenceAbbreviation>
    <referenceNumber>28</referenceNumber>
    <SBLAbbreviation>Hos</SBLAbbreviation>
    <OSISAbbreviation>Hos</OSISAbbreviation>
    <CCELNumber>28</CCELNumber>
    <ParatextAbbreviation>Hos</ParatextAbbreviation>
    <ParatextNumber>28</ParatextNumber>
    <NETBibleAbbreviation>Hos</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Joel</nameEnglish>
    <referenceAbbreviation>JOL</referenceAbbreviation>
    <referenceNumber>29</referenceNumber>
    <SBLAbbreviation>Joel</SBLAbbreviation>
    <OSISAbbreviation>Joel</OSISAbbreviation>
    <CCELNumber>29</CCELNumber>
    <ParatextAbbreviation>Jol</ParatextAbbreviation>
    <ParatextNumber>29</ParatextNumber>
    <NETBibleAbbreviation>Joe</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Amos</nameEnglish>
    <referenceAbbreviation>AMO</referenceAbbreviation>
    <referenceNumber>30</referenceNumber>
    <SBLAbbreviation>Amos</SBLAbbreviation>
    <OSISAbbreviation>Amos</OSISAbbreviation>
    <CCELNumber>30</CCELNumber>
    <ParatextAbbreviation>Amo</ParatextAbbreviation>
    <ParatextNumber>30</ParatextNumber>
    <NETBibleAbbreviation>Amo</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Obadiah</nameEnglish>
    <referenceAbbreviation>OBA</referenceAbbreviation>
    <referenceNumber>31</referenceNumber>
    <SBLAbbreviation>Obad</SBLAbbreviation>
    <OSISAbbreviation>Obad</OSISAbbreviation>
    <CCELNumber>31</CCELNumber>
    <ParatextAbbreviation>Oba</ParatextAbbreviation>
    <ParatextNumber>31</ParatextNumber>
    <NETBibleAbbreviation>Oba</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Jonah</nameEnglish>
    <referenceAbbreviation>JON</referenceAbbreviation>
    <referenceNumber>32</referenceNumber>
    <SBLAbbreviation>Jonah</SBLAbbreviation>
    <OSISAbbreviation>Jonah</OSISAbbreviation>
    <CCELNumber>32</CCELNumber>
    <ParatextAbbreviation>Jon</ParatextAbbreviation>
    <ParatextNumber>32</ParatextNumber>
    <NETBibleAbbreviation>Jon</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Micah</nameEnglish>
    <referenceAbbreviation>MIC</referenceAbbreviation>
    <referenceNumber>33</referenceNumber>
    <SBLAbbreviation>Nic</SBLAbbreviation>
    <OSISAbbreviation>Mic</OSISAbbreviation>
    <CCELNumber>33</CCELNumber>
    <ParatextAbbreviation>Mic</ParatextAbbreviation>
    <ParatextNumber>33</ParatextNumber>
    <NETBibleAbbreviation>Mic</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Nahum</nameEnglish>
    <referenceAbbreviation>NAM</referenceAbbreviation>
    <referenceNumber>34</referenceNumber>
    <SBLAbbreviation>Nah</SBLAbbreviation>
    <OSISAbbreviation>Nah</OSISAbbreviation>
    <CCELNumber>34</CCELNumber>
    <ParatextAbbreviation>Nam</ParatextAbbreviation>
    <ParatextNumber>34</ParatextNumber>
    <NETBibleAbbreviation>Nah</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Habakkuk</nameEnglish>
    <referenceAbbreviation>HAB</referenceAbbreviation>
    <referenceNumber>35</referenceNumber>
    <SBLAbbreviation>Hab</SBLAbbreviation>
    <OSISAbbreviation>Hab</OSISAbbreviation>
    <CCELNumber>35</CCELNumber>
    <ParatextAbbreviation>Hab</ParatextAbbreviation>
    <ParatextNumber>35</ParatextNumber>
    <NETBibleAbbreviation>Hab</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Zephaniah</nameEnglish>
    <referenceAbbreviation>ZEP</referenceAbbreviation>
    <referenceNumber>36</referenceNumber>
    <SBLAbbreviation>Zeph</SBLAbbreviation>
    <OSISAbbreviation>Zeph</OSISAbbreviation>
    <CCELNumber>36</CCELNumber>
    <ParatextAbbreviation>Zep</ParatextAbbreviation>
    <ParatextNumber>36</ParatextNumber>
    <NETBibleAbbreviation>Zep</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Haggai</nameEnglish>
    <referenceAbbreviation>HAG</referenceAbbreviation>
    <referenceNumber>37</referenceNumber>
    <SBLAbbreviation>Hag</SBLAbbreviation>
    <OSISAbbreviation>Hag</OSISAbbreviation>
    <CCELNumber>37</CCELNumber>
    <ParatextAbbreviation>Hag</ParatextAbbreviation>
    <ParatextNumber>37</ParatextNumber>
    <NETBibleAbbreviation>Hag</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Zechariah</nameEnglish>
    <referenceAbbreviation>ZEC</referenceAbbreviation>
    <referenceNumber>38</referenceNumber>
    <SBLAbbreviation>Zech</SBLAbbreviation>
    <OSISAbbreviation>Zech</OSISAbbreviation>
    <CCELNumber>38</CCELNumber>
    <ParatextAbbreviation>Zec</ParatextAbbreviation>
    <ParatextNumber>38</ParatextNumber>
    <NETBibleAbbreviation>Zec</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Malachi</nameEnglish>
    <referenceAbbreviation>MAL</referenceAbbreviation>
    <referenceNumber>39</referenceNumber>
    <SBLAbbreviation>Mal</SBLAbbreviation>
    <OSISAbbreviation>Mal</OSISAbbreviation>
    <CCELNumber>39</CCELNumber>
    <ParatextAbbreviation>Mal</ParatextAbbreviation>
    <ParatextNumber>39</ParatextNumber>
    <NETBibleAbbreviation>Mal</NETBibleAbbreviation>
  </BibleBookCodes>

<!-- New Testament -->
  <BibleBookCodes>
    <nameEnglish>Matthew</nameEnglish>
    <referenceAbbreviation>MAT</referenceAbbreviation>
    <referenceNumber>40</referenceNumber>
    <SBLAbbreviation>Matt</SBLAbbreviation>
    <OSISAbbreviation>Matt</OSISAbbreviation>
    <CCELNumber>40</CCELNumber>
    <ParatextAbbreviation>Mat</ParatextAbbreviation>
    <ParatextNumber>41</ParatextNumber>
    <NETBibleAbbreviation>Mat</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Mark</nameEnglish>
    <referenceAbbreviation>MRK</referenceAbbreviation>
    <referenceNumber>41</referenceNumber>
    <SBLAbbreviation>Mark</SBLAbbreviation>
    <OSISAbbreviation>Mark</OSISAbbreviation>
    <CCELNumber>41</CCELNumber>
    <ParatextAbbreviation>Mrk</ParatextAbbreviation>
    <ParatextNumber>42</ParatextNumber>
    <NETBibleAbbreviation>Mar</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Luke</nameEnglish>
    <referenceAbbreviation>LUK</referenceAbbreviation>
    <referenceNumber>42</referenceNumber>
    <SBLAbbreviation>Luke</SBLAbbreviation>
    <OSISAbbreviation>Luke</OSISAbbreviation>
    <CCELNumber>42</CCELNumber>
    <ParatextAbbreviation>Luk</ParatextAbbreviation>
    <ParatextNumber>43</ParatextNumber>
    <NETBibleAbbreviation>Luk</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>John</nameEnglish>
    <referenceAbbreviation>JHN</referenceAbbreviation>
    <referenceNumber>43</referenceNumber>
    <SBLAbbreviation>John</SBLAbbreviation>
    <OSISAbbreviation>John</OSISAbbreviation>
    <CCELNumber>43</CCELNumber>
    <ParatextAbbreviation>Jhn</ParatextAbbreviation>
    <ParatextNumber>44</ParatextNumber>
    <NETBibleAbbreviation>Joh</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Acts</nameEnglish>
    <referenceAbbreviation>ACT</referenceAbbreviation>
    <referenceNumber>44</referenceNumber>
    <SBLAbbreviation>Acts</SBLAbbreviation>
    <OSISAbbreviation>Acts</OSISAbbreviation>
    <CCELNumber>44</CCELNumber>
    <ParatextAbbreviation>Act</ParatextAbbreviation>
    <ParatextNumber>45</ParatextNumber>
    <NETBibleAbbreviation>Act</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Romans</nameEnglish>
    <referenceAbbreviation>ROM</referenceAbbreviation>
    <referenceNumber>45</referenceNumber>
    <SBLAbbreviation>Rom</SBLAbbreviation>
    <OSISAbbreviation>Rom</OSISAbbreviation>
    <CCELNumber>45</CCELNumber>
    <ParatextAbbreviation>Rom</ParatextAbbreviation>
    <ParatextNumber>46</ParatextNumber>
    <NETBibleAbbreviation>Rom</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Corinthians</nameEnglish>
    <referenceAbbreviation>CO1</referenceAbbreviation>
    <referenceNumber>46</referenceNumber>
    <SBLAbbreviation>1 Cor</SBLAbbreviation>
    <OSISAbbreviation>1Cor</OSISAbbreviation>
    <CCELNumber>46</CCELNumber>
    <ParatextAbbreviation>1Co</ParatextAbbreviation>
    <ParatextNumber>47</ParatextNumber>
    <NETBibleAbbreviation>1Co</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>2 Corinthians</nameEnglish>
    <referenceAbbreviation>CO2</referenceAbbreviation>
    <referenceNumber>47</referenceNumber>
    <SBLAbbreviation>2 Cor</SBLAbbreviation>
    <OSISAbbreviation>2Cor</OSISAbbreviation>
    <CCELNumber>47</CCELNumber>
    <ParatextAbbreviation>2Co</ParatextAbbreviation>
    <ParatextNumber>48</ParatextNumber>
    <NETBibleAbbreviation>2Co</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Galatians</nameEnglish>
    <referenceAbbreviation>GAL</referenceAbbreviation>
    <referenceNumber>48</referenceNumber>
    <SBLAbbreviation>Gal</SBLAbbreviation>
    <OSISAbbreviation>Gal</OSISAbbreviation>
    <CCELNumber>48</CCELNumber>
    <ParatextAbbreviation>Gal</ParatextAbbreviation>
    <ParatextNumber>49</ParatextNumber>
    <NETBibleAbbreviation>Gal</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Ephesians</nameEnglish>
    <referenceAbbreviation>EPH</referenceAbbreviation>
    <referenceNumber>49</referenceNumber>
    <SBLAbbreviation>Eph</SBLAbbreviation>
    <OSISAbbreviation>Eph</OSISAbbreviation>
    <CCELNumber>49</CCELNumber>
    <ParatextAbbreviation>Eph</ParatextAbbreviation>
    <ParatextNumber>50</ParatextNumber>
    <NETBibleAbbreviation>Eph</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Philippians</nameEnglish>
    <referenceAbbreviation>PHP</referenceAbbreviation>
    <referenceNumber>50</referenceNumber>
    <SBLAbbreviation>Phil</SBLAbbreviation>
    <OSISAbbreviation>Phil</OSISAbbreviation>
    <CCELNumber>50</CCELNumber>
    <ParatextAbbreviation>Php</ParatextAbbreviation>
    <ParatextNumber>51</ParatextNumber>
    <NETBibleAbbreviation>Phi</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>Colossians</nameEnglish>
    <referenceAbbreviation>COL</referenceAbbreviation>
    <referenceNumber>51</referenceNumber>
    <SBLAbbreviation>Col</SBLAbbreviation>
    <OSISAbbreviation>Col</OSISAbbreviation>
    <CCELNumber>51</CCELNumber>
    <ParatextAbbreviation>Col</ParatextAbbreviation>
    <ParatextNumber>52</ParatextNumber>
    <NETBibleAbbreviation>Col</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Thessalonians</nameEnglish>
    <referenceAbbreviation>TH1</referenceAbbreviation>
    <referenceNumber>52</referenceNumber>
    <SBLAbbreviation>1 Thess</SBLAbbreviation>
    <OSISAbbreviation>1Thess</OSISAbbreviation>
    <CCELNumber>52</CCELNumber>
    <ParatextAbbreviation>1Th</ParatextAbbreviation>
    <ParatextNumber>53</ParatextNumber>
    <NETBibleAbbreviation>1Th</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>2 Thessalonians</nameEnglish>
    <referenceAbbreviation>TH2</referenceAbbreviation>
    <referenceNumber>53</referenceNumber>
    <SBLAbbreviation>2 Thess</SBLAbbreviation>
    <OSISAbbreviation>2Thess</OSISAbbreviation>
    <CCELNumber>53</CCELNumber>
    <ParatextAbbreviation>2Th</ParatextAbbreviation>
    <ParatextNumber>54</ParatextNumber>
    <NETBibleAbbreviation>2Th</NETBibleAbbreviation>
  </BibleBookCodes>
  <BibleBookCodes>
    <nameEnglish>1 Timothy</nameEnglish>