<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of Bible booknames codes including
    A ID number (1..n for processing only)
    An English book name (as a comment only)
        (This table should be language agnostic although English is used as a meta-language.)
    A three character reference code (upper case, no spaces, begin with a letter)
    The SBL abbreviation (can include spaces)
    The OSIS abbrevation (no spaces but may begin with a digit)
    The three-character Paratext abbreviation (no spaces but may begin with a digit)
    The two-digit Paratext number
All of the above fields should be unique.
Deutero-canonical/Apocryphal books are included.
"Combined" books are included.

The data is preceded by a header of the same format as an OSIS header.

Note that the data is supplied as XML elements, not attributes.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleBooksNames [
    <!ELEMENT BibleBooksNames (header,BibleBookNames+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier+,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleBookNames (id,nameEnglish,referenceAbbreviation,SBLAbbreviation?,OSISAbbreviation?,ParatextAbbreviation?,ParatextNumber?)>
            <!ELEMENT id (#PCDATA)>
            <!ELEMENT nameEnglish (#PCDATA)>
            <!ELEMENT referenceAbbreviation (#PCDATA)>
            <!ELEMENT SBLAbbreviation (#PCDATA)>
            <!ELEMENT OSISAbbreviation (#PCDATA)>
            <!ELEMENT ParatextAbbreviation (#PCDATA)>
            <!ELEMENT ParatextNumber (#PCDATA)>
]>

<BibleBooksNames>

  <header>
    <work>
      <version>0.10</version>
      <date>2010-10-12</date>
      <title>Bible books names list</title>
      <contributor role="com">Robert Hunt</contributor>
      <identifier type="URL">http://www.sbl-site.org/publications/publishingwithsbl.aspx</identifier>
      <identifier type="URL">http://www.bibletechnologies.net</identifier>
      <rights>Public Domain</rights>
    </work>
  </header>

  <BibleBookNames languageCode="eng">
    <BibleBookName id="1" referenceAbbreviation="GEN">
      <defaultName>Genesis<defaultName>
      <defaultLongName>The book of Genesis</defaultLongName>
      <defaultAbbreviation>Gen</defaultAbbreviation>
    </BibleBookName>
  </BibleBookNames>

</BibleBooksNames>

======================
  <BibleBookNames>
    <id>2</id>
    <nameEnglish>Exodus</nameEnglish>
    <referenceAbbreviation>EXO</referenceAbbreviation>
    <SBLAbbreviation>Exod</SBLAbbreviation>
    <OSISAbbreviation>Exod</OSISAbbreviation>
    <ParatextAbbreviation>Exo</ParatextAbbreviation>
    <ParatextNumber>02</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>3</id>
    <nameEnglish>Leviticus</nameEnglish>
    <referenceAbbreviation>LEV</referenceAbbreviation>
    <SBLAbbreviation>Lev</SBLAbbreviation>
    <OSISAbbreviation>Lev</OSISAbbreviation>
    <ParatextAbbreviation>Lev</ParatextAbbreviation>
    <ParatextNumber>03</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>4</id>
    <nameEnglish>Numbers</nameEnglish>
    <referenceAbbreviation>NUM</referenceAbbreviation>
    <SBLAbbreviation>Num</SBLAbbreviation>
    <OSISAbbreviation>Num</OSISAbbreviation>
    <ParatextAbbreviation>Num</ParatextAbbreviation>
    <ParatextNumber>04</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>5</id>
    <nameEnglish>Deuteronomy</nameEnglish>
    <referenceAbbreviation>DEU</referenceAbbreviation>
    <SBLAbbreviation>Deut</SBLAbbreviation>
    <OSISAbbreviation>Deut</OSISAbbreviation>
    <ParatextAbbreviation>Deu</ParatextAbbreviation>
    <ParatextNumber>05</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>6</id>
    <nameEnglish>Joshua</nameEnglish>
    <referenceAbbreviation>JOS</referenceAbbreviation>
    <SBLAbbreviation>Josh</SBLAbbreviation>
    <OSISAbbreviation>Josh</OSISAbbreviation>
    <ParatextAbbreviation>Jos</ParatextAbbreviation>
    <ParatextNumber>06</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>7</id>
    <nameEnglish>Judges</nameEnglish>
    <referenceAbbreviation>JDG</referenceAbbreviation>
    <SBLAbbreviation>Judg</SBLAbbreviation>
    <OSISAbbreviation>Judg</OSISAbbreviation>
    <ParatextAbbreviation>Jdg</ParatextAbbreviation>
    <ParatextNumber>07</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>8</id>
    <nameEnglish>Ruth</nameEnglish>
    <referenceAbbreviation>RUT</referenceAbbreviation>
    <SBLAbbreviation>Ruth</SBLAbbreviation>
    <OSISAbbreviation>Ruth</OSISAbbreviation>
    <ParatextAbbreviation>Rut</ParatextAbbreviation>
    <ParatextNumber>08</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>9</id>
    <nameEnglish>1 Samuel</nameEnglish>
    <referenceAbbreviation>SA1</referenceAbbreviation>
    <SBLAbbreviation>1 Sam</SBLAbbreviation>
    <OSISAbbreviation>1Sam</OSISAbbreviation>
    <ParatextAbbreviation>1Sa</ParatextAbbreviation>
    <ParatextNumber>09</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>10</id>
    <nameEnglish>2 Samuel</nameEnglish>
    <referenceAbbreviation>SA2</referenceAbbreviation>
    <SBLAbbreviation>2 Sam</SBLAbbreviation>
    <OSISAbbreviation>2Sam</OSISAbbreviation>
    <ParatextAbbreviation>2Sa</ParatextAbbreviation>
    <ParatextNumber>10</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>11</id>
    <nameEnglish>1 Kings</nameEnglish>
    <referenceAbbreviation>KI1</referenceAbbreviation>
    <SBLAbbreviation>1 Kgs</SBLAbbreviation>
    <OSISAbbreviation>1Kgs</OSISAbbreviation>
    <ParatextAbbreviation>1Ki</ParatextAbbreviation>
    <ParatextNumber>11</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>12</id>
    <nameEnglish>2 Kings</nameEnglish>
    <referenceAbbreviation>KI2</referenceAbbreviation>
    <SBLAbbreviation>2 Kgs</SBLAbbreviation>
    <OSISAbbreviation>2Kgs</OSISAbbreviation>
    <ParatextAbbreviation>2Ki</ParatextAbbreviation>
    <ParatextNumber>12</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>13</id>
    <nameEnglish>1 Chronicles</nameEnglish>
    <referenceAbbreviation>CH1</referenceAbbreviation>
    <SBLAbbreviation>1 Chr</SBLAbbreviation>
    <OSISAbbreviation>1Chr</OSISAbbreviation>
    <ParatextAbbreviation>1Ch</ParatextAbbreviation>
    <ParatextNumber>13</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>14</id>
    <nameEnglish>2 Chronicles</nameEnglish>
    <referenceAbbreviation>CH2</referenceAbbreviation>
    <SBLAbbreviation>2 Chr</SBLAbbreviation>
    <OSISAbbreviation>2Chr</OSISAbbreviation>
    <ParatextAbbreviation>2Ch</ParatextAbbreviation>
    <ParatextNumber>14</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>15</id>
    <nameEnglish>Ezra</nameEnglish>
    <referenceAbbreviation>EZR</referenceAbbreviation>
    <SBLAbbreviation>Ezra</SBLAbbreviation>
    <OSISAbbreviation>Ezra</OSISAbbreviation>
    <ParatextAbbreviation>Ezr</ParatextAbbreviation>
    <ParatextNumber>15</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>16</id>
    <nameEnglish>Nehemiah</nameEnglish>
    <referenceAbbreviation>NEH</referenceAbbreviation>
    <SBLAbbreviation>Neh</SBLAbbreviation>
    <OSISAbbreviation>Neh</OSISAbbreviation>
    <ParatextAbbreviation>Neh</ParatextAbbreviation>
    <ParatextNumber>16</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>17</id>
    <nameEnglish>Esther</nameEnglish>
    <referenceAbbreviation>EST</referenceAbbreviation>
    <SBLAbbreviation>Esth</SBLAbbreviation>
    <OSISAbbreviation>Esth</OSISAbbreviation>
    <ParatextAbbreviation>Est</ParatextAbbreviation>
    <ParatextNumber>17</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>18</id>
    <nameEnglish>Job</nameEnglish>
    <referenceAbbreviation>JOB</referenceAbbreviation>
    <SBLAbbreviation>Job</SBLAbbreviation>
    <OSISAbbreviation>Job</OSISAbbreviation>
    <ParatextAbbreviation>Job</ParatextAbbreviation>
    <ParatextNumber>18</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>19</id>
    <nameEnglish>Psalms</nameEnglish>
    <referenceAbbreviation>PSA</referenceAbbreviation>
    <SBLAbbreviation>Ps</SBLAbbreviation>
    <OSISAbbreviation>Ps</OSISAbbreviation>
    <ParatextAbbreviation>Psa</ParatextAbbreviation>
    <ParatextNumber>19</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>20</id>
    <nameEnglish>Proverbs</nameEnglish>
    <referenceAbbreviation>PRO</referenceAbbreviation>
    <SBLAbbreviation>Prov</SBLAbbreviation>
    <OSISAbbreviation>Prov</OSISAbbreviation>
    <ParatextAbbreviation>Pro</ParatextAbbreviation>
    <ParatextNumber>20</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>21</id>
    <nameEnglish>Ecclesiastes</nameEnglish>
    <referenceAbbreviation>ECC</referenceAbbreviation>
    <SBLAbbreviation>Eccl</SBLAbbreviation>
    <OSISAbbreviation>Eccl</OSISAbbreviation>
    <ParatextAbbreviation>Ecc</ParatextAbbreviation>
    <ParatextNumber>21</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>22</id>
    <nameEnglish>Song of Solomon</nameEnglish>
    <referenceAbbreviation>SNG</referenceAbbreviation>
    <SBLAbbreviation>Song</SBLAbbreviation>
    <OSISAbbreviation>Song</OSISAbbreviation>
    <ParatextAbbreviation>Sng</ParatextAbbreviation>
    <ParatextNumber>22</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>23</id>
    <nameEnglish>Isaiah</nameEnglish>
    <referenceAbbreviation>ISA</referenceAbbreviation>
    <SBLAbbreviation>Isa</SBLAbbreviation>
    <OSISAbbreviation>Isa</OSISAbbreviation>
    <ParatextAbbreviation>Isa</ParatextAbbreviation>
    <ParatextNumber>23</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>24</id>
    <nameEnglish>Jeremiah</nameEnglish>
    <referenceAbbreviation>JER</referenceAbbreviation>
    <SBLAbbreviation>Jer</SBLAbbreviation>
    <OSISAbbreviation>Jer</OSISAbbreviation>
    <ParatextAbbreviation>Jer</ParatextAbbreviation>
    <ParatextNumber>24</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>25</id>
    <nameEnglish>Lamentations</nameEnglish>
    <referenceAbbreviation>LAM</referenceAbbreviation>
    <SBLAbbreviation>Lam</SBLAbbreviation>
    <OSISAbbreviation>Lam</OSISAbbreviation>
    <ParatextAbbreviation>Lam</ParatextAbbreviation>
    <ParatextNumber>25</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>26</id>
    <nameEnglish>Ezekiel</nameEnglish>
    <referenceAbbreviation>EZK</referenceAbbreviation>
    <SBLAbbreviation>Ezek</SBLAbbreviation>
    <OSISAbbreviation>Ezek</OSISAbbreviation>
    <ParatextAbbreviation>Ezk</ParatextAbbreviation>
    <ParatextNumber>26</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>27</id>
    <nameEnglish>Daniel</nameEnglish>
    <referenceAbbreviation>DAN</referenceAbbreviation>
    <SBLAbbreviation>Dan</SBLAbbreviation>
    <OSISAbbreviation>Dan</OSISAbbreviation>
    <ParatextAbbreviation>Dan</ParatextAbbreviation>
    <ParatextNumber>27</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>28</id>
    <nameEnglish>Hosea</nameEnglish>
    <referenceAbbreviation>HOS</referenceAbbreviation>
    <SBLAbbreviation>Hos</SBLAbbreviation>
    <OSISAbbreviation>Hos</OSISAbbreviation>
    <ParatextAbbreviation>Hos</ParatextAbbreviation>
    <ParatextNumber>28</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>29</id>
    <nameEnglish>Joel</nameEnglish>
    <referenceAbbreviation>JOL</referenceAbbreviation>
    <SBLAbbreviation>Joel</SBLAbbreviation>
    <OSISAbbreviation>Joel</OSISAbbreviation>
    <ParatextAbbreviation>Jol</ParatextAbbreviation>
    <ParatextNumber>29</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>30</id>
    <nameEnglish>Amos</nameEnglish>
    <referenceAbbreviation>AMO</referenceAbbreviation>
    <SBLAbbreviation>Amos</SBLAbbreviation>
    <OSISAbbreviation>Amos</OSISAbbreviation>
    <ParatextAbbreviation>Amo</ParatextAbbreviation>
    <ParatextNumber>30</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>31</id>
    <nameEnglish>Obadiah</nameEnglish>
    <referenceAbbreviation>OBA</referenceAbbreviation>
    <SBLAbbreviation>Obad</SBLAbbreviation>
    <OSISAbbreviation>Obad</OSISAbbreviation>
    <ParatextAbbreviation>Oba</ParatextAbbreviation>
    <ParatextNumber>31</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>32</id>
    <nameEnglish>Jonah</nameEnglish>
    <referenceAbbreviation>JON</referenceAbbreviation>
    <SBLAbbreviation>Jonah</SBLAbbreviation>
    <OSISAbbreviation>Jonah</OSISAbbreviation>
    <ParatextAbbreviation>Jon</ParatextAbbreviation>
    <ParatextNumber>32</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>33</id>
    <nameEnglish>Micah</nameEnglish>
    <referenceAbbreviation>MIC</referenceAbbreviation>
    <SBLAbbreviation>Nic</SBLAbbreviation>
    <OSISAbbreviation>Mic</OSISAbbreviation>
    <ParatextAbbreviation>Mic</ParatextAbbreviation>
    <ParatextNumber>33</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>34</id>
    <nameEnglish>Nahum</nameEnglish>
    <referenceAbbreviation>NAM</referenceAbbreviation>
    <SBLAbbreviation>Nah</SBLAbbreviation>
    <OSISAbbreviation>Nah</OSISAbbreviation>
    <ParatextAbbreviation>Nam</ParatextAbbreviation>
    <ParatextNumber>34</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>35</id>
    <nameEnglish>Habakkuk</nameEnglish>
    <referenceAbbreviation>HAB</referenceAbbreviation>
    <SBLAbbreviation>Hab</SBLAbbreviation>
    <OSISAbbreviation>Hab</OSISAbbreviation>
    <ParatextAbbreviation>Hab</ParatextAbbreviation>
    <ParatextNumber>35</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>36</id>
    <nameEnglish>Zephaniah</nameEnglish>
    <referenceAbbreviation>ZEP</referenceAbbreviation>
    <SBLAbbreviation>Zeph</SBLAbbreviation>
    <OSISAbbreviation>Zeph</OSISAbbreviation>
    <ParatextAbbreviation>Zep</ParatextAbbreviation>
    <ParatextNumber>36</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>37</id>
    <nameEnglish>Haggai</nameEnglish>
    <referenceAbbreviation>HAG</referenceAbbreviation>
    <SBLAbbreviation>Hag</SBLAbbreviation>
    <OSISAbbreviation>Hag</OSISAbbreviation>
    <ParatextAbbreviation>Hag</ParatextAbbreviation>
    <ParatextNumber>37</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>38</id>
    <nameEnglish>Zechariah</nameEnglish>
    <referenceAbbreviation>ZEC</referenceAbbreviation>
    <SBLAbbreviation>Zech</SBLAbbreviation>
    <OSISAbbreviation>Zech</OSISAbbreviation>
    <ParatextAbbreviation>Zec</ParatextAbbreviation>
    <ParatextNumber>38</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>39</id>
    <nameEnglish>Malachi</nameEnglish>
    <referenceAbbreviation>MAL</referenceAbbreviation>
    <SBLAbbreviation>Mal</SBLAbbreviation>
    <OSISAbbreviation>Mal</OSISAbbreviation>
    <ParatextAbbreviation>Mal</ParatextAbbreviation>
    <ParatextNumber>39</ParatextNumber>
  </BibleBookNames>

  <BibleBookNames>
    <id>40</id>
    <nameEnglish>Matthew</nameEnglish>
    <referenceAbbreviation>MAT</referenceAbbreviation>
    <SBLAbbreviation>Matt</SBLAbbreviation>
    <OSISAbbreviation>Matt</OSISAbbreviation>
    <ParatextAbbreviation>Mat</ParatextAbbreviation>
    <ParatextNumber>41</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>41</id>
    <nameEnglish>Mark</nameEnglish>
    <referenceAbbreviation>MRK</referenceAbbreviation>
    <SBLAbbreviation>Mark</SBLAbbreviation>
    <OSISAbbreviation>Mark</OSISAbbreviation>
    <ParatextAbbreviation>Mrk</ParatextAbbreviation>
    <ParatextNumber>42</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>42</id>
    <nameEnglish>Luke</nameEnglish>
    <referenceAbbreviation>LUK</referenceAbbreviation>
    <SBLAbbreviation>Luke</SBLAbbreviation>
    <OSISAbbreviation>Luke</OSISAbbreviation>
    <ParatextAbbreviation>Luk</ParatextAbbreviation>
    <ParatextNumber>43</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>43</id>
    <nameEnglish>John</nameEnglish>
    <referenceAbbreviation>JHN</referenceAbbreviation>
    <SBLAbbreviation>John</SBLAbbreviation>
    <OSISAbbreviation>John</OSISAbbreviation>
    <ParatextAbbreviation>Jhn</ParatextAbbreviation>
    <ParatextNumber>44</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>44</id>
    <nameEnglish>Acts</nameEnglish>
    <referenceAbbreviation>ACT</referenceAbbreviation>
    <SBLAbbreviation>Acts</SBLAbbreviation>
    <OSISAbbreviation>Acts</OSISAbbreviation>
    <ParatextAbbreviation>Act</ParatextAbbreviation>
    <ParatextNumber>45</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>45</id>
    <nameEnglish>Romans</nameEnglish>
    <referenceAbbreviation>ROM</referenceAbbreviation>
    <SBLAbbreviation>Rom</SBLAbbreviation>
    <OSISAbbreviation>Rom</OSISAbbreviation>
    <ParatextAbbreviation>Rom</ParatextAbbreviation>
    <ParatextNumber>46</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>46</id>
    <nameEnglish>1 Corinthians</nameEnglish>
    <referenceAbbreviation>CO1</referenceAbbreviation>
    <SBLAbbreviation>1 Cor</SBLAbbreviation>
    <OSISAbbreviation>1Cor</OSISAbbreviation>
    <ParatextAbbreviation>1Co</ParatextAbbreviation>
    <ParatextNumber>47</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>47</id>
    <nameEnglish>2 Corinthians</nameEnglish>
    <referenceAbbreviation>CO2</referenceAbbreviation>
    <SBLAbbreviation>2 Cor</SBLAbbreviation>
    <OSISAbbreviation>2Cor</OSISAbbreviation>
    <ParatextAbbreviation>2Co</ParatextAbbreviation>
    <ParatextNumber>48</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>48</id>
    <nameEnglish>Galatians</nameEnglish>
    <referenceAbbreviation>GAL</referenceAbbreviation>
    <SBLAbbreviation>Gal</SBLAbbreviation>
    <OSISAbbreviation>Gal</OSISAbbreviation>
    <ParatextAbbreviation>Gal</ParatextAbbreviation>
    <ParatextNumber>49</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>49</id>
    <nameEnglish>Ephesians</nameEnglish>
    <referenceAbbreviation>EPH</referenceAbbreviation>
    <SBLAbbreviation>Eph</SBLAbbreviation>
    <OSISAbbreviation>Eph</OSISAbbreviation>
    <ParatextAbbreviation>Eph</ParatextAbbreviation>
    <ParatextNumber>50</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>50</id>
    <nameEnglish>Philippians</nameEnglish>
    <referenceAbbreviation>PHP</referenceAbbreviation>
    <SBLAbbreviation>Phil</SBLAbbreviation>
    <OSISAbbreviation>Phil</OSISAbbreviation>
    <ParatextAbbreviation>Php</ParatextAbbreviation>
    <ParatextNumber>51</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>51</id>
    <nameEnglish>Colossians</nameEnglish>
    <referenceAbbreviation>COL</referenceAbbreviation>
    <SBLAbbreviation>Col</SBLAbbreviation>
    <OSISAbbreviation>Col</OSISAbbreviation>
    <ParatextAbbreviation>Col</ParatextAbbreviation>
    <ParatextNumber>52</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>52</id>
    <nameEnglish>1 Thessalonians</nameEnglish>
    <referenceAbbreviation>TH1</referenceAbbreviation>
    <SBLAbbreviation>1 Thess</SBLAbbreviation>
    <OSISAbbreviation>1Thess</OSISAbbreviation>
    <ParatextAbbreviation>1Th</ParatextAbbreviation>
    <ParatextNumber>53</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>53</id>
    <nameEnglish>2 Thessalonians</nameEnglish>
    <referenceAbbreviation>TH2</referenceAbbreviation>
    <SBLAbbreviation>2 Thess</SBLAbbreviation>
    <OSISAbbreviation>2Thess</OSISAbbreviation>
    <ParatextAbbreviation>2Th</ParatextAbbreviation>
    <ParatextNumber>54</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>54</id>
    <nameEnglish>1 Timothy</nameEnglish>
    <referenceAbbreviation>TI1</referenceAbbreviation>
    <SBLAbbreviation>1 Tim</SBLAbbreviation>
    <OSISAbbreviation>1Tim</OSISAbbreviation>
    <ParatextAbbreviation>1Ti</ParatextAbbreviation>
    <ParatextNumber>55</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>55</id>
    <nameEnglish>2 Timothy</nameEnglish>
    <referenceAbbreviation>TI2</referenceAbbreviation>
    <SBLAbbreviation>2 Tim</SBLAbbreviation>
    <OSISAbbreviation>2Tim</OSISAbbreviation>
    <ParatextAbbreviation>2Ti</ParatextAbbreviation>
    <ParatextNumber>56</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>56</id>
    <nameEnglish>Titus</nameEnglish>
    <referenceAbbreviation>TIT</referenceAbbreviation>
    <SBLAbbreviation>Titus</SBLAbbreviation>
    <OSISAbbreviation>Titus</OSISAbbreviation>
    <ParatextAbbreviation>Tit</ParatextAbbreviation>
    <ParatextNumber>57</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>57</id>
    <nameEnglish>Philemon</nameEnglish>
    <referenceAbbreviation>PHM</referenceAbbreviation>
    <SBLAbbreviation>Phlm</SBLAbbreviation>
    <OSISAbbreviation>Phlm</OSISAbbreviation>
    <ParatextAbbreviation>Phm</ParatextAbbreviation>
    <ParatextNumber>58</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>58</id>
    <nameEnglish>Hebrews</nameEnglish>
    <referenceAbbreviation>HEB</referenceAbbreviation>
    <SBLAbbreviation>Heb</SBLAbbreviation>
    <OSISAbbreviation>Heb</OSISAbbreviation>
    <ParatextAbbreviation>Heb</ParatextAbbreviation>
    <ParatextNumber>59</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>59</id>
    <nameEnglish>James</nameEnglish>
    <referenceAbbreviation>JAS</referenceAbbreviation>
    <SBLAbbreviation>Jas</SBLAbbreviation>
    <OSISAbbreviation>Jas</OSISAbbreviation>
    <ParatextAbbreviation>Jas</ParatextAbbreviation>
    <ParatextNumber>60</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>60</id>
    <nameEnglish>1 Peter</nameEnglish>
    <referenceAbbreviation>PE1</referenceAbbreviation>
    <SBLAbbreviation>1 Pet</SBLAbbreviation>
    <OSISAbbreviation>1Pet</OSISAbbreviation>
    <ParatextAbbreviation>1Pe</ParatextAbbreviation>
    <ParatextNumber>61</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>61</id>
    <nameEnglish>2 Peter</nameEnglish>
    <referenceAbbreviation>PE2</referenceAbbreviation>
    <SBLAbbreviation>2 Pet</SBLAbbreviation>
    <OSISAbbreviation>2Pet</OSISAbbreviation>
    <ParatextAbbreviation>2Pe</ParatextAbbreviation>
    <ParatextNumber>62</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>62</id>
    <nameEnglish>1 John</nameEnglish>
    <referenceAbbreviation>JN1</referenceAbbreviation>
    <SBLAbbreviation>1 John</SBLAbbreviation>
    <OSISAbbreviation>1John</OSISAbbreviation>
    <ParatextAbbreviation>1Jn</ParatextAbbreviation>
    <ParatextNumber>63</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>63</id>
    <nameEnglish>2 John</nameEnglish>
    <referenceAbbreviation>JN2</referenceAbbreviation>
    <SBLAbbreviation>2 John</SBLAbbreviation>
    <OSISAbbreviation>2John</OSISAbbreviation>
    <ParatextAbbreviation>2Jn</ParatextAbbreviation>
    <ParatextNumber>64</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>64</id>
    <nameEnglish>3John</nameEnglish>
    <referenceAbbreviation>JN3</referenceAbbreviation>
    <SBLAbbreviation>3 John</SBLAbbreviation>
    <OSISAbbreviation>3John</OSISAbbreviation>
    <ParatextAbbreviation>3Jn</ParatextAbbreviation>
    <ParatextNumber>65</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>65</id>
    <nameEnglish>Jude</nameEnglish>
    <referenceAbbreviation>JUD</referenceAbbreviation>
    <SBLAbbreviation>Jude</SBLAbbreviation>
    <OSISAbbreviation>Jude</OSISAbbreviation>
    <ParatextAbbreviation>Jud</ParatextAbbreviation>
    <ParatextNumber>66</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>66</id>
    <nameEnglish>Revelation</nameEnglish>
    <referenceAbbreviation>REV</referenceAbbreviation>
    <SBLAbbreviation>Rev</SBLAbbreviation>
    <OSISAbbreviation>Rev</OSISAbbreviation>
    <ParatextAbbreviation>Rev</ParatextAbbreviation>
    <ParatextNumber>67</ParatextNumber>
  </BibleBookNames>

  <BibleBookNames>
    <id>67</id>
    <nameEnglish>Baruch</nameEnglish>
    <referenceAbbreviation>BAR</referenceAbbreviation>
    <SBLAbbreviation>Bar</SBLAbbreviation>
    <OSISAbbreviation>Bar</OSISAbbreviation>
    <ParatextAbbreviation>Bar</ParatextAbbreviation>
    <ParatextNumber>73</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>68</id>
    <nameEnglish>Daniel additions</nameEnglish>
    <referenceAbbreviation>DNA</referenceAbbreviation>
    <SBLAbbreviation>Add Dan</SBLAbbreviation>
    <OSISAbbreviation>AddDan</OSISAbbreviation>
  </BibleBookNames>
  <BibleBookNames>
    <id>69</id>
    <nameEnglish>Prayer of Azariah</nameEnglish>
    <referenceAbbreviation>PAZ</referenceAbbreviation>
    <SBLAbbreviation>Pr Azar</SBLAbbreviation>
    <OSISAbbreviation>PrAzar</OSISAbbreviation>
  </BibleBookNames>
  <BibleBookNames>
    <id>70</id>
    <nameEnglish>Bel and the dragon</nameEnglish>
    <referenceAbbreviation>BEL</referenceAbbreviation>
    <SBLAbbreviation>Bel</SBLAbbreviation>
    <OSISAbbreviation>Bel</OSISAbbreviation>
    <ParatextAbbreviation>Bel</ParatextAbbreviation>
    <ParatextNumber>77</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>71</id>
    <nameEnglish>Song of the three young men</nameEnglish>
    <referenceAbbreviation>S3Y</referenceAbbreviation>
    <SBLAbbreviation>Sg Three</SBLAbbreviation>
    <OSISAbbreviation>SgThree</OSISAbbreviation>
    <ParatextAbbreviation>S3Y</ParatextAbbreviation>
    <ParatextNumber>75</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>72</id>
    <nameEnglish>Susanna</nameEnglish>
    <referenceAbbreviation>SUS</referenceAbbreviation>
    <SBLAbbreviation>Sus</SBLAbbreviation>
    <OSISAbbreviation>Sus</OSISAbbreviation>
    <ParatextAbbreviation>Sus</ParatextAbbreviation>
    <ParatextNumber>76</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>73</id>
    <nameEnglish>1 Esdras</nameEnglish>
    <referenceAbbreviation>ES1</referenceAbbreviation>
    <SBLAbbreviation>1 Esd</SBLAbbreviation>
    <OSISAbbreviation>1Esd</OSISAbbreviation>
    <ParatextAbbreviation>1Es</ParatextAbbreviation>
    <ParatextNumber>82</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>74</id>
    <nameEnglish>2 Esdras</nameEnglish>
    <referenceAbbreviation>ES2</referenceAbbreviation>
    <SBLAbbreviation>2 Esd</SBLAbbreviation>
    <OSISAbbreviation>2Esd</OSISAbbreviation>
    <ParatextAbbreviation>2Es</ParatextAbbreviation>
    <ParatextNumber>83</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>75</id>
    <nameEnglish>Greek Esther</nameEnglish>
    <referenceAbbreviation>ESG</referenceAbbreviation>
    <SBLAbbreviation>Add Esth</SBLAbbreviation>
    <OSISAbbreviation>AddEsth</OSISAbbreviation>
    <ParatextAbbreviation>EsG</ParatextAbbreviation>
    <ParatextNumber>70</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>76</id>
    <nameEnglish>Epistle of Jeremiah</nameEnglish>
    <referenceAbbreviation>LJE</referenceAbbreviation>
    <SBLAbbreviation>Ep Jer</SBLAbbreviation>
    <OSISAbbreviation>EpJer</OSISAbbreviation>
    <ParatextAbbreviation>LJe</ParatextAbbreviation>
    <ParatextNumber>74</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>77</id>
    <nameEnglish>Judith</nameEnglish>
    <referenceAbbreviation>JDT</referenceAbbreviation>
    <SBLAbbreviation>Jdt</SBLAbbreviation>
    <OSISAbbreviation>Jdt</OSISAbbreviation>
    <ParatextAbbreviation>Jdt</ParatextAbbreviation>
    <ParatextNumber>69</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>78</id>
    <nameEnglish>1 Maccabees</nameEnglish>
    <referenceAbbreviation>MA1</referenceAbbreviation>
    <SBLAbbreviation>1 Macc</SBLAbbreviation>
    <OSISAbbreviation>1Macc</OSISAbbreviation>
    <ParatextAbbreviation>1Ma</ParatextAbbreviation>
    <ParatextNumber>78</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>79</id>
    <nameEnglish>2 Maccabees</nameEnglish>
    <referenceAbbreviation>MA2</referenceAbbreviation>
    <SBLAbbreviation>2 Macc</SBLAbbreviation>
    <OSISAbbreviation>2Macc</OSISAbbreviation>
    <ParatextAbbreviation>2Ma</ParatextAbbreviation>
    <ParatextNumber>79</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>80</id>
    <nameEnglish>3 Maccabees</nameEnglish>
    <referenceAbbreviation>MA3</referenceAbbreviation>
    <SBLAbbreviation>3 Macc</SBLAbbreviation>
    <OSISAbbreviation>3Macc</OSISAbbreviation>
    <ParatextAbbreviation>3Ma</ParatextAbbreviation>
    <ParatextNumber>80</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>81</id>
    <nameEnglish>4 Maccabees</nameEnglish>
    <referenceAbbreviation>MA4</referenceAbbreviation>
    <SBLAbbreviation>4 Macc</SBLAbbreviation>
    <OSISAbbreviation>4Macc</OSISAbbreviation>
    <ParatextAbbreviation>4Ma</ParatextAbbreviation>
    <ParatextNumber>81</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>82</id>
    <nameEnglish>Prayer of Manaseeh</nameEnglish>
    <referenceAbbreviation>MAN</referenceAbbreviation>
    <SBLAbbreviation>Pr Man</SBLAbbreviation>
    <OSISAbbreviation>PrMan</OSISAbbreviation>
    <ParatextAbbreviation>Man</ParatextAbbreviation>
    <ParatextNumber>84</ParatextNumber>
  </BibleBookNames>
  <BibleBookNames>
    <id>83</id>
    <nameEnglish>Sirach/Ecclesiasticus</nameEnglish>
    <referenceAbbreviation>SIR</referenceAbbreviation>