<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of Bible booknames codes including
    A ID number (1..n for processing only)
    An English book name (as a comment only)
        (This table should be language agnostic although English is used as a meta-language.)
    A three character reference code (upper case, no spaces, begin with a letter)
    The SBL abbreviation (can include spaces)
    The OSIS abbrevation (no spaces but may begin with a digit)
    The three-character Paratext abbreviation (no spaces but may begin with a digit)
    The two-digit Paratext number
All of the above fields should be unique.
Deutero-canonical/Apocryphal books are included.
"Combined" books are included.

The data is preceded by a header of the same format as an OSIS header.

Note that the data is supplied as XML elements, not attributes.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleBooksNames [
    <!ELEMENT BibleBooksNames (header,BibleBookNames+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier+,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleBookNames (defaultName,defaultLongName,defaultAbbreviation)>
            <!ELEMENT defaultName (#PCDATA)>
            <!ELEMENT defaultLongName (#PCDATA)>
            <!ELEMENT defaultAbbreviation (#PCDATA)>
]>

<BibleBooksNames>

  <header>
    <work>
      <version>0.10</version>
      <date>2010-11-03</date>
      <title>Bible books names list</title>
      <contributor role="com">Robert Hunt</contributor>
      <identifier type="URL">http://www.sbl-site.org/publications/publishingwithsbl.aspx</identifier>
      <identifier type="URL">http://www.bibletechnologies.net</identifier>
      <rights>Public Domain</rights>
    </work>
  </header>

  <BibleBookNames referenceAbbreviation="GEN" id="1">
    <defaultName>Genesis</defaultName>
      <defaultLongName>The book of Genesis</defaultLongName>
      <defaultAbbreviation>Gen</defaultAbbreviation>
    </BibleBookNames>

</BibleBooksNames>
