<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of Bible book reference abbreviations in the order that they are included in the given publication.
    The list of the available 3-character book reference abbreviations can be found in BibleBooksCodes.xml
    An ascending id number is also included as an attribute for convenience.

It must contain entries only for the books actually included in a given publication.
This file can be copied, renamed, and edited if your publication contains different books or in a different order.

The data entries in this file are language agnostic, i.e., the information can apply to a publication in any language.

The data is preceded by a header of the same format as an OSIS header.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleBookOrderSystem [
    <!ELEMENT BibleBookOrderSystem (header,book+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier*,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|cre|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT book (#PCDATA)>
            <!ATTLIST book id CDATA #REQUIRED>
]>

<BibleBookOrderSystem>

  <header>
    <work>
      <version>0.91</version>
      <date>2010-12-01</date>
      <title>Matigsalug Manobo NT+ book order</title>
      <contributor role="com">Robert Hunt</contributor>
      <rights>Public Domain</rights>
    </work>
  </header>

  <book id="1">GEN</book>
  <book id="2">RUT</book>
  <book id="3">EST</book>
  <book id="4">JNA</book>
  <!-- Yes, this volume contains only four OT books -->
  <book id="5">MAT</book>
  <book id="6">MRK</book>
  <book id="7">LUK</book>
  <book id="8">JHN</book>
  <book id="9">ACT</book>
  <book id="10">ROM</book>
  <book id="11">CO1</book>
  <book id="12">CO2</book>
  <book id="13">GAL</book>
  <book id="14">EPH</book>
  <book id="15">PHP</book>
  <book id="16">COL</book>
  <book id="17">TH1</book>
  <book id="18">TH2</book>
  <book id="19">TI1</book>
  <book id="20">TI2</book>
  <book id="21">TIT</book>
  <book id="22">PHM</book>
  <book id="23">HEB</book>
  <book id="24">JAM</book>
  <book id="25">PE1</book>
  <book id="26">PE2</book>
  <book id="27">JN1</book>
  <book id="28">JN2</book>
  <book id="29">JN3</book>
  <book id="30">JDE</book>
  <book id="31">REV</book>
</BibleBookOrderSystem>
